name: AutoWrite

options:
  bundleIdPrefix: com.autowrite

targets:
  AutoWrite:
    type: application
    platform: iOS
    deploymentTarget: "17.0"

    sources:
      - AutoWrite

    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.autowrite.app
      PRODUCT_NAME: "Auto Fire"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      SWIFT_VERSION: "5.0"
      TARGETED_DEVICE_FAMILY: "1,2"
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_CFBundleDisplayName: "Auto Fire"
