name: AutoWrite

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install XcodeGen
        run: |
          brew install xcodegen

      - name: Generate Xcode Project
        run: |
          xcodegen generate

      - name: Build
        run: |
          xcodebuild \
            -project AutoWrite.xcodeproj \
            -scheme AutoWrite \
            -sdk iphoneos \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            build

      - name: Package IPA
        run: |
          mkdir -p Payload

          cp -R \
            build/Build/Products/Release-iphoneos/AutoWrite.app \
            Payload/

          zip -r AutoWrite-unsigned.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: AutoWrite-IPA
          path: AutoWrite-unsigned.ipa
